# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isdn',
            new_name='isbn',
        ),
    ]
